name: Github Environment 
on: 
  push:
    branches:
      - "main"
  
jobs:
  deploy:
    runs-on: ubuntu-18.04
    
    environment:
      name: prodduction
      url: https://github.com/IHEEB22/GithubActionLab
  
    steps:
      - name: print environment secret 
        run: echo "${{secrets.APP_SECRET}}"
