name: Github Environment 
on: 
  push:
    branches:
      - "main"
  workflow_dispatch:  
      
jobs:
  deploy:
    runs-on: ubuntu-18.04
    
    environment:
      name: staging
      url: https://github.com/IHEEB22/GithubActionLab
  
    steps:
      - name: print environment secret 
        run: echo "${{secrets.DOCKER_HUB_PASSOWRD}}"
