name: Build and Test
on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build code
        run: |
          echo "npm install"
          echo "npm run build hello"
      - name: Test code
        run: echo "npm test"