name: Build and Publish NPM Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

  test:
    runs-on: windowswindows-latest
    steps:
    - name: run simple command on runer
      run : pwd

  push_container:
    runs-on: macos-latest
    steps:
    - name: push to dockerHub 
      run: echo "hello macos"
    needs: [build, test]
