name: Github Self Hosted Runner
on: 
  push:
    branches:
      - "main"
  workflow_dispatch:
    
      
jobs:
  deploy:
    runs-on: self-hosted  
    
    steps:
      - name: assigne a job to an self hosted runner  
        run: echo "hello from Standard_b1s azure vm"
