name: Add environment variable and print it 
on: 
  push:
    branches:
      - "main"
  workflow_dispatch:  
      
jobs:
  deploy:
    runs-on: ubuntu-18.04
    
    steps:
      - name: add an env to github envirement variable 
        run: echo  "env1=test" >> "$GITHUB_ENV"
      
      - name: print env1
        run: echo  ${{env.env1}}
        